name: Capture screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"  # Weekly (Mon 03:00 UTC)

permissions:
  contents: write

jobs:
  capture:
    runs-on: ubuntu-latest
    env:
      # Add more URLs later in PAGES (JSON array) if you want multiple pages.
      PAGES: '["https://sagarvs614.wixsite.com/plants-planet"]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Capture screenshots
        run: npm run capture

      - name: Commit screenshots
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add screenshots/*.png || true
          git commit -m "chore: update screenshots" || echo "No changes to commit"
          git push
